<a href="https://colab.research.google.com/github/IsabellaGarciaS/Biosignals/blob/main/P1_Python_SolanllyMontoya.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
### Solanlly Evenedy Montoya Rivera cc 1001244569 Lab v6-8 grupo 2

### PUNTO A. Crear los siguientes vectores

import numpy as np #Primero debemos importar la biblioteca para trabajar con matrices
import random as rg
import matplotlib.pyplot as plt #Importar esta libreria para poder graficar

a= np.array([67.1, 1, -0.3, 5.2, -6])
b= np.array([1, 3, 2.2, 5.1, 1])
print('vector a='+ str(a))
print('vector b='+ str(b))
print(' ')

### PUNTO B. Mulriplicacion escalar

multiplicacion = np.sum(a * b)
# Que se debe realizar para poder multiplicar los dos vectores? Se debe utilizar la función np.sum() esta devuelve la suma de todos los
# elementos y como usamos parentesis entonces calcula la suma de los productos de los elementos de los vectores a y b.

### PUNTO C. Multiplicacion punto a punto

multiplicacion2 = a * b

### PUNTO D. Crear la siguiente matriz

A = np.array([[2, -1, -3],[4, -1.5, -2.5],[7.3, -0.9, -0.2]])
print('matriz A')
print(A)
print(' ')

### PUNTO E. Obtengo su transpuesta

ATranspuesta = np.transpose(A)
ATranspuesta1 = A.T #esta es otra forma de hacer el mismo comando asi se encuentra en las diapos
print('Transpuesta A')
print(ATranspuesta)
print(' ')

### PUNTO F. Comando de la libreria numpy

rg = np.random.default_rng(1)
a0 = np.ones(6) #crea una matriz de ceros con la forma especificada.
a1 = np.floor(10*rg.random((3,3))) #devuelve los elementos de una matriz hacia abajo al entero más cercano.
a2 = np.ceil(10*rg.random((3,3))) #deveulve el valor entero hacia arriba
a3 = np.round(10*rg.random((3,3))) #devuelve el valor con las cifras decimales especificadas

### PUNTO G. Obtengo la primera fila, tercera columan de la matriz

respuesta = A[0, 2]
print('punto G = El valor de la 1ra fila 3ra columna es '+ str(respuesta))

### PUNTO H. Obtengo la segunda fila de la matriz

respuesta2 = A[1 ]
print('punto H = La 2da fila de la matriz es '+ str(respuesta2))

### PUNTO I. Forma y tamaño de la matriz

x1 = A.ndim #dimensionalidad
x2 = A.size #tamaño total
x3 = A.shape #forma
print('punto I = '+'dimensionalidad:' + str(x1) + ' tamaño:' + str(x2)+ ' forma:' + str(x3))
print('   ')

vector a=[67.1  1.  -0.3  5.2 -6. ]
vector b=[1.  3.  2.2 5.1 1. ]
 
matriz A
[[ 2.  -1.  -3. ]
 [ 4.  -1.5 -2.5]
 [ 7.3 -0.9 -0.2]]
 
Transpuesta A
[[ 2.   4.   7.3]
 [-1.  -1.5 -0.9]
 [-3.  -2.5 -0.2]]
 
punto G = El valor de la 1ra fila 3ra columna es -3.0
punto H = La 2da fila de la matriz es [ 4.  -1.5 -2.5]
punto I = dimensionalidad:2 tamaño:9 forma:(3, 3)
   


In [ ]:
### PUNTO J. Construir una funcion seno

n=np.arange(0, 81) # hago un intervalo de 0-80

def y(n):
  return np.sin(np.pi*0.18*n)
valores = y(n)

plt.plot(n, valores, color="red")
plt.title("Funcion seno")
plt.xlabel("n")
plt.ylabel("y[n]")
plt.grid(True)
plt.show()

### PUNTO K. Construir una funcion coseno

n= np.arange(0, 81)
def y2(n):
  return np.cos(2*np.pi*0.03*n)
valores2= y2(n)

plt.plot(n, valores2, color="green")
plt.title("Funcion coseno")
plt.xlabel("n")
plt.ylabel("y[n]")
plt.grid(True)
plt.show()

### PUNTO L

# Para la suma de las dos señales
def suma(n):
  return y(n) + y2(n)

valores3 = suma(n)
plt.plot(n, valores3, color="blue")
plt.title("Suma de funciones")
plt.xlabel("n")
plt.ylabel("y[n]+ y2[n]")
plt.grid(True)
plt.show()

# Para la multiplicaciion de las dos señales
def multip(n):
  return y(n) * y2(n)

valores4 = multip(n)
plt.plot(n, valores4, color="magenta")
plt.title("Multiplicacion de funciones")
plt.xlabel("n")
plt.ylabel("y[n]*y2[n]")
plt.grid(True)
plt.show()

### PUNTO M

plt.plot(n, valores, color='blue', label="y[n]")
plt.plot(n, valores2, color='green', label="y2[n]")
plt.title("GRAFICA PUNTO M")
plt.xlabel("n")
plt.ylabel("f(x)")
plt.legend()
plt.show()

### PUNTO N

plt.plot(n, valores3, color='orange', label="y[n]+ y2[n]")
plt.plot(n, valores4, color='purple', label="y[n]*y2[n]")
plt.title("GRAFICA PUNTO N")
plt.xlabel("n")
plt.ylabel("f(x)")
plt.legend()
plt.show()


In [2]:
####### RETO ########

import pandas as pd

nota = {'Sol':5.0, 'Danna':4.5, 'isa':2.0, 'Eve': 3.0, 'Jorge': 2.9, 'Diana': 3.5, 'Rosa': 4.0, 'Daniela': 1.5, 'Camila': 3.0, 'Bayron': 2.5}  #diccionario que contiene las notas de los estudiantes

def calificaciones(nota): #creamos la funcion
    nota = pd.Series(nota) #función de la libreria de pandas que usa para crear una serie a partir del diccionario que creamos 'nota'
    datos = pd.Series([nota.min(), nota.max(), nota.mean(), nota.std()]) #aca se calcula lo que necesitamos
    return datos # aca devolvemos una serie con los resultados

resultado=calificaciones(nota) #llama a la funcion calificaciones y le pasa los argumentos que serian las notas del diccionario, eso lo guarde en una variable para no confundirme despues

print('   ')
print('Resultado de analisis de notas de los estudiantes del curso: ')
print("Nota minima: {0:.2f}".format(resultado[0]))
print("Nota maxima: {0:.2f}".format(resultado[1]))
print("Nota promedio: {0:.2f}".format(resultado[2]))
print("Desviacion estandar: {0:.2f}".format(resultado[3]))


   
Resultado de analisis de notas de los estudiantes del curso: 
Nota minima: 1.50
Nota maxima: 5.00
Nota promedio: 3.19
Desviacion estandar: 1.09
